### ISSUE TITLE
Export in php7 geht nicht

### ISSUE THREAD

**Issue by RexDude** [cmsone/cmsone#15]

**Comment by fietstouring** [comment]
welcher export? Import/Export-Funktion?

**Comment by RexDude** [comment]
Ja genau.
Bei mir kommt: ` Notice: Undefined offset: 0 in /home/www/cmsone/website/redaxo/include/classes/class.rex_sql.inc.php on line 35` x mal und der Export ist viel zu klein.

Da wir aber noch nicht die gleichen Versionen einsetzen muss das noch warten bis ich hier auf GitHub das ganze committed habe.

**Comment by fietstouring** [comment]
function_import_export.inc.php 337
$sql->getValue($idx) liefert NULL

`while ($sql->hasNext()) {
                $record = array();

                foreach ($fields as $idx => $type) {
                    $column = $sql->getValue($idx);

                    switch ($type) {
                        case 'int':
                            $record[] = intval($column);
                            break;
                        case 'double':
                            $record[] = sprintf('%.10F', (double) $column);
                            break;
                        case 'string':
                        default:
                            $record[] = $sql->escape($column, "'", true);
                            break;
                    }
                }

                $values[] = $nl . '  (' . implode(',', $record) . ')';
                $sql->next();
            }

            if (!empty($values)) {
                $values = implode(',', $values);
                
                fwrite($fp, "\nINSERT INTO `$table` VALUES $values;");
                unset($values);
            }
        } while ($sql->getRows() >= $max);

        if ($start > 0) {
            fwrite($fp, "\n/*!40000 ALTER TABLE `$table` ENABLE KEYS */;");
            fwrite($fp, "\nUNLOCK TABLES;\n\n");
        }`

**Comment by fietstouring** [comment]
damit gehts, dafür kommen da dann aber Warnings in xform, mit "deiner funktion" kommen keine warnings in xform...

`function mysqli_result($result,$row,$field=0) {
    if ($result===false) return false;
    if ($row>=mysqli_num_rows($result)) return false;
    if (is_string($field) && !(strpos($field,".")===false)) {
        $t_field=explode(".",$field);
        $field=-1;
        $t_fields=mysqli_fetch_fields($result);
        for ($id=0;$id<mysqli_num_fields($result);$id++) {
            if ($t_fields[$id]->table==$t_field[0] && $t_fields[$id]->name==$t_field[1]) {
                $field=$id;
                break;
            }
        }
        if ($field==-1) return false;
    }
    mysqli_data_seek($result,$row);
    $line=mysqli_fetch_array($result);
    return isset($line[$field])?$line[$field]:false;
}`

**Comment by RexDude** [comment]
Kann dich gerade nicht gut unterstützen. Ich hätte mal die mysql:result wrapper funktion von hier verwendet: https://github.com/dshafik/php7-mysql-shim

**Comment by RexDude** [comment]
oder die ganze lib versuchen. aber dann ohne die patches.

**Comment by fietstouring** [comment]
hab die ganze lib eingebunden.
hab folgendes getestet:

Export 
SEO42 pathlist
string_table
metainfos setzen
developer

es kommen teilweise Warnings, keine Errors.



Xform: 
Warning: mysql_result(): Default not found in MySQL result index 000000006a3b28930000000172990e56 in /Users/Shared/Dropbox/htdocs/_php7test/redaxo/include/mysql.php on line 260
Warning: mysql_result(Default): Initial error found in file /Users/Shared/Dropbox/htdocs/_php7test/redaxo/include/classes/class.rex_sql.inc.php on line 799

Kategorie-Metainfos schreiben:
Warning: mysql_result(cat_test_meta): Initial error found in file /Users/Shared/Dropbox/htdocs/_php7test/redaxo/include/addons/metainfo/extensions/extension_common.inc.php on line 57
Warning: mysql_result(cat_test_meta): Initial error found in file /Users/Shared/Dropbox/htdocs/_php7test/redaxo/include/addons/metainfo/extensions/extension_common.inc.php on line 64
Warning: mysql_result(cat_test_meta): Initial error found in file /Users/Shared/Dropbox/htdocs/_php7test/redaxo/include/addons/metainfo/extensions/extension_common.inc.php on line 94

**Comment by RexDude** [comment]
Ok wieder zruück zur Version die sonst gefunzt hat.
Komischerweise wird machmal als $field eine Zahl bzw ein Index übergeben, d.h. man muss auf is_numeric prüfen, dann geht der Export. Hier die neue Funktion. Bitte mal einbauen und damit arbeiten damit wir sehen ob nicht noch was auftaucht. XFform Prob ist mir auch schon klar, aber Lösung noch nicht ganz.

```php
// * wrapper for mysql_result, taken from http://stackoverflow.com/a/31986858
// * added is_numeric check from http://mariolurig.com/coding/mysqli_result-function-to-match-mysql_result/
// * Thx!
function mysqli_result($result, $row, $field) {
    $result->data_seek($row);

    // for no table prefix just go ahead and fetch assoc
    if ( strstr($field, ".") === false ) {
        // Fetch result array
        // $data = $result->fetch_assoc(); old, has problems if $field is an int value
		if (is_numeric($field)) {
			$data = mysqli_fetch_row($result);
		} else {
			$data = mysqli_fetch_assoc($result);
		}

        return $data[$field];
    }

    // workaround for assoc use and overwriting fieldnames like "a.timestamp" and "b.timestamp"
    list($tablename,$fieldname) = explode(".",$field);
    $resultData = $result->fetch_array(MYSQLI_NUM);

    foreach( $result->fetch_fields() as $index => $fieldData ) {
        if ( $fieldData->table == $tablename && $fieldData->name == $fieldname ) {
            return $resultData[$index]; 
        }
    }

    return false;
}
```

**Comment by fietstouring** [comment]
D.h. du willst nicht diese shim klasse verwenden, sondern die mysql funktionen umbennen... 
Für das mysql_real_escape_string brauchts dann auch noch was, mit dem shim geht das ja zumindest in xform was ich gesehen hab, 
lg
Am 24.02.2016 23:57 schrieb RexDude <notifications@github.com>:Ok wieder zruück zur Version die sonst gefunzt hat.
Komischerweise wird machmal als $field eine Zahl bzw ein Index übergeben, d.h. man muss auf is_numeric prüfen, dann geht der Export. Hier die neue Funktion. Bitte mal einbauen und damit arbeiten damit wir sehen ob nicht noch was auftaucht. XFform Prob ist mir auch schon klar, aber Lösung noch nicht ganz.

// * wrapper for mysql_result, taken from http://stackoverflow.com/a/31986858
// * added is_numeric check from http://mariolurig.com/coding/mysqli_result-function-to-match-mysql_result/
// * Thx!
function mysqli_result($result, $row, $field) {
    $result->data_seek($row);

    // for no table prefix just go ahead and fetch assoc
    if ( strstr($field, ".") === false ) {
        // Fetch result array
        // $data = $result->fetch_assoc(); old, has problems if $field is an int value
        if (is_numeric($field)) {
            $data = mysqli_fetch_row($result);
        } else {
            $data = mysqli_fetch_assoc($result);
        }

        return $data[$field];
    }

    // workaround for assoc use and overwriting fieldnames like "a.timestamp" and "b.timestamp"
    list($tablename,$fieldname) = explode(".",$field);
    $resultData = $result->fetch_array(MYSQLI_NUM);

    foreach( $result->fetch_fields() as $index => $fieldData ) {
        if ( $fieldData->table == $tablename && $fieldData->name == $fieldname ) {
            return $resultData[$index]; 
        }
    }

    return false;
}

**Comment by RexDude** [comment]
> D.h. du willst nicht diese shim klasse verwenden, sondern die mysql funktionen umbennen...

Ja aufjedefall...

> Für das mysql_real_escape_string brauchts dann auch noch was, mit dem shim geht das ja zumindest in xform was ich gesehen hab,

ok. ich fange bald an hier auf github, dann haben wir eine version auf die wir uns genau beziehen können.
