### ISSUE TITLE
Finaler Name für V1 abklären

### ISSUE THREAD

**Issue by RexDude** [cmsone/cmsone#26]
* CMS One
* CMS One R4
* CMS One R4 Edition
* CMS One REDAXO4 Edition
* RexOne

---------------------------

Es wäre auch ein Name mit REDAXO am Anfang denkbar aber wegen (R) weiss ich net wie das rechtlich ist und iauch moralisch evtl. bedenklich (also noch mehr als das ganze Projekt eh schon ist) ;D :P

* REDAXO One
* REDAXO 4 OneEdition

---------------------------

Wie einige der Namen wirken kann man hier in den Screens abchecken:
http://www.cmsone.org/version-1.html

**Comment by FfdE** [comment]
Das wichtigste aus Anwendersicht, ist für mich, ein einfacher, eleganter Name. Ein Office, das sein CMS intensiv benutzt, muss dessen Namen ein dutzendmal pro Tag aussprechen und über die Tische rufen :). Also möglichst einsilbig, ein  Wort und etwas das nicht allzu doof tönt. Geh mal ins "One" find ich etwas doof. "Redaxo" war gut, weil das Wort sonst keine Bedeutung hat, wenn auch etwas lang.

**Comment by RexDude** [comment]
"Geh mal ins CMS One..." heisst es dann aber enstprechend  wenn du bei REDAXO eh keine Abkürzung gewählt hast ;) Und das hört sich gut an finde ich :)

**Comment by FfdE** [comment]
Das wird dann auf "CMS" gekürzt.

**Comment by RexDude** [comment]
Geh mal ins Bodhi ist aber auch nix ;)
Kannst ja bessere Namen vorschgen. Wir können sammeln und später ne Abstimmung machen um mal die.. ähh.. Community (?) Tendenz zu ermitteln.

**Comment by FfdE** [comment]
Geh mal ins Flow hingegen wär cool. Kommt halt etwas aufs Wort drauf an.

**Comment by RexDude** [comment]
Falls man sich für RexOne als Ableger bzw. Vorläufer zu CMS One entscheidet könntest du deinen "Geh mal ins REDAXO..." Word-flow erstmal behalten ;)

**Comment by RexDude** [comment]
Bin mir schon sehr sicher:
Es bleibt hier beim Namen CMS One :)
