### ISSUE TITLE
Lizenzrechtliches abklären

### ISSUE THREAD

**Issue by RexDude** [cmsone/cmsone#27]
Idee:

* CMS One V1 unter MIT
* R4 Unterbau so wie gehabt, also 1:1 übernehmen

Kann man dass doppellizensieren oder muss ich die GPL nehmen wie R4??? Oder brauchts kein MIT???

**Comment by skerbis** [comment]
Wirst dich an die GPL halten müssen. Deinen eigenen Code kannste als MIT veröffentlichen. Viel Spaß bei der Dokumentation.

**Comment by RexDude** [comment]
Danke :)

**Comment by skerbis** [comment]
Ein guter Hinweis: http://programmers.stackexchange.com/a/234032

**Comment by RexDude** [comment]
Man könnts auch alles weiter unter GPL laufen lassen.
Weisst du zufällig wie dass ist wenn man bestehenden code abändern will, sprich Funktionsnamen ändern etc.? Sollte ja kein Thema sein oder? Sonst macht Open Source vermutlich auch keine Sinn mehr...

**Comment by skerbis** [comment]
Sofern dein code open ist und nachverfolgbar

**Comment by RexDude** [comment]
Ok, Cool :)

**Comment by skerbis** [comment]
Grundsätzlich sehe ich das so: Urheber nennen, nicht vergraulen ... dann ist alles ok

**Comment by RexDude** [comment]
Ja das auf jedefall.
