### ISSUE TITLE
default pages "Home" and "404"

### ISSUE THREAD

**Issue by alexplusde** [cmsone/cmsone#29]
As cms1 will primarily be used as a Website-CMS, two articles should already be set up: Home and 404. I've seen some lazy web developers forcing the error article to be home - this should be avoided by already providing these articles (and the default values in cms1's "setup" page).

template id of those articles should be "1" (even if template 1 does not exist after setup, it's still better than "0")

**Comment by starlord** [comment]
I am not sure if "forcing" is the right way to do here. I was thinking of offering a boilerplate starterpack for this case. but of course you should stay free organizing your articles as you wish.

**Comment by alexplusde** [comment]
i wasn't sure, too. But imho, it will fit for 99% of all projects and can be undone easily.

**Comment by starlord** [comment]
There will be no forced setup of articles, instead boilerplate/demo will do show the "right" way to setup project.
