### ISSUE TITLE
[seo42] update seo42 tools (page rank, webmaster tools...)

### ISSUE THREAD

**Issue by alexplusde** [cmsone/cmsone#30]
PageRank: should be obsolet now
Webmaster Tools: is now called "Search Console"

cms1 could provide more help for best practice here, like linking to Sistrix Resources:
DE: https://www.sistrix.de/resources/
EN: https://www.sistrix.com/resources/

We should collect more helpful links here.

**Comment by starlord** [comment]
This page should only be a starting point of seo resources. I am not planning to change here anything in the future except obsolete links etc.
