### ISSUE TITLE
Addons: Link to forum / bug report for every addon

### ISSUE THREAD

**Issue by alexplusde** [cmsone/cmsone#31]
administrators should always have access to help and report issues by adding a "help" tab which may links to github and/or cms1 forum and/or redaxo forum.

![image](https://cloud.githubusercontent.com/assets/3855487/14234215/6bf2f132-f9dd-11e5-8e93-a452763d3599.png)

**Comment by starlord** [comment]
btw: there are no seperate repositorys for shipped addons in CMS One.

**Comment by starlord** [comment]
I am planning a help link in footer instead of credits.
