### ISSUE TITLE
[be_utilities/global_template] "global template" obsolet? (backend utilites)

### ISSUE THREAD

**Issue by alexplusde** [cmsone/cmsone#32]
Wasn't the global template just a hack for providing a source code field to add classes/functions via CMS UI? 

Shouldn't it be replaced by a "global functions" plugin which provides a source code field for that particular reason and save it inside addon's/plugin's data-folder?

**Comment by starlord** [comment]
Global template has the advantage that it will be contained in the export.
Now that we have a cool resources folder that belongs to the cms I am planing havin a library folder with that folder. This I wanted to do for version 2 but in version 1 it is also possible.

You should really stop thinking in addons/plugins ;)

**Comment by alexplusde** [comment]
While import/export is a good reason, it still has nothing to do with templates at all, I think. Just wanted to report it. :)

Yeah, it's "force of habit" ;)

**Comment by starlord** [comment]
> While import/export is a good reason, it still has nothing to do with templates at all, I think. Just wanted to report it. :)

this is of course true ;)

**Comment by starlord** [comment]
so that plan is then to remove the plugin and add resources/library folder.

**Comment by starlord** [comment]
library funcionality has bean added, see resources dir. global_template plugin will be removed later too.
