### ISSUE TITLE
spelling "Add-on" (Duden)

### ISSUE THREAD

**Issue by alexplusde** [cmsone/cmsone#33]
I know, it's not the most important thing on your to-do-list, but: It's called Add-on / Add-ons, not AddOns.
http://www.duden.de/rechtschreibung/Add_on

I already reported that to redaxo a few years ago but they never changed it. I think it's spelled wrong on more places than just the menu.

**Comment by starlord** [comment]
this won't happen for version 1 anymore. version 2 maybe.
