### ISSUE TITLE
[xform] missing key [translate:xform_create_template]

### ISSUE THREAD

**Issue by alexplusde** [cmsone/cmsone#34]
![image](https://cloud.githubusercontent.com/assets/3855487/14234364/2759992c-f9e2-11e5-9a01-5aa0673bbbb2.png)

**Comment by starlord** [comment]
hint: You can add [addonname] prefix to issue title if you refer to an addon/plugin.

**Comment by starlord** [comment]
@alexplusde xform_create_template= ???

**Comment by alexplusde** [comment]
The key used to be shown as an Icon in Redaxo > xForm > E-Mail Templates:
```<img src="media/template_plus.gif" alt="[translate:xform_create_template]" title="Template erstellen">```
![image](https://cloud.githubusercontent.com/assets/3855487/14383640/adc14d5e-fd96-11e5-90cb-a306307021c6.png)

now it's like this:
![image](https://cloud.githubusercontent.com/assets/3855487/14383627/a2e86930-fd96-11e5-92ed-eff2331f9e23.png)
